embed maps and layers with apikey
geosolutions-it/geonode pull request #1258
Opened 2022-04-23 14:33 UTC by giohappy

Custom PR to support `apikey` (access token) authentication for embedded maps, layers and proxy requests. It works also with lockdown mode (specific case for MapStand).

2022-04-23 14:53 UTC, giohappy commented
@marthamareal to test this PR you have to do the following:

 - set LOCKDOWN_GEONODE=True
 - create a a layer and a map
 - grab an access token from Django Admin -> Django OAuth Toolkit -> Access Tokens
 - logout from GeoNode
 - load an embedded layer with `/layers/<layername>/embed?apikey=<access_token>` -> you can see and query the layer
 - load an embedded map with `/maps/<pk>/embed?apikey=<access_token>` -> you can see and query the map
 - remove the apikey from the URLs -> you get 403 Forbidden

2022-04-23 21:16 UTC, mattiagiupponi approved these changes

2022-04-26 08:26 UTC, marthamareal commented
@giohappy i have tested with the above steps, however, i do not get 403 on loading the embedded layer/map without the apikey

2022-04-26 09:00 UTC, marthamareal requested changes

2022-04-26 14:52 UTC, giohappy commented on geonode/security/middleware.py
> +        '/layers/(?P<mapid>[^/]+)/embed',
done

2022-04-26 14:53 UTC, merged