33Av style improvement
geosolutions-it/geonode pull request #1683
Opened 2023-12-15 15:17 UTC by mattiagiupponi

<Include a few sentences describing the overall goals for this Pull Request>

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

For all pull requests:

- [ ] Confirm you have read the [contribution guidelines](https://github.com/GeoNode/geonode/blob/master/CONTRIBUTING.md) 
- [ ] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in the documentation)
- [ ] Make sure the first PR targets the master branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.

The following are required only for core and extension modules (they are welcomed, but not required, for contrib modules):
- [ ] There is a ticket in https://github.com/GeoNode/geonode/issues describing the issue/improvement/feature (a notable exemption is, changes not visible to end-users)
- [ ] The issue connected to the PR must have Labels and Milestone assigned
- [ ] PR for bug fixes and small new features are presented as a single commit
- [ ] Commit message must be in the form "[Fixes #<issue_number>] Title of the Issue"
- [ ] New unit tests have been added covering the changes, unless there is an explanation on why the tests are not necessary/implemented
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] This PR passes the QA checks: black geonode && flake8 geonode
- [ ] Commits changing the **settings**, **UI**, **existing user workflows**, or adding **new functionality**, need to include documentation updates
- [ ] Commits adding **new texts** do use gettext and have updated .po / .mo files (without location infos)

**Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or inapplicable.**

2023-12-15 15:17 UTC, mattiagiupponi commented
https://github.com/GeoNode/geoserver-restconfig/pull/43

2023-12-18 11:49 UTC, etj requested changes
pls improve the `wsname_stylename` checks

2023-12-18 11:49 UTC, etj commented on geonode/geoserver/helpers.py
> +            name=saved_layer.name, workspace=saved_layer.workspace))
Not sure if we should consider all the cases:
- stylename: global (may exist, we risk to delete default sytles anyway)
  - not implemented -- do we need it?
- stylename in wsname (it can be easily spotted in deployed geoserver) 
  - implemented
- `wsname`_`stylename`: global (see next comment w/ screenshot)
  - not implemented --  we DO need it
- `wsname`_`stylename` in wsname (see next comment w/ screenshot)
  - implemented

2023-12-18 11:49 UTC, etj commented on geonode/geoserver/helpers.py
> +            name=f"{saved_layer.workspace}_{saved_layer.name}", workspace=saved_layer.workspace))
It seems that styles prepended with "geonode_" are both global and in the geonode workspace
![image](https://github.com/geosolutions-it/geonode/assets/717359/cd8f7b50-911a-4066-8afa-b7841a91fd94)

2023-12-22 17:08 UTC, closed without merging